
waymark:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 'docker.for.mac.localhost'
      schema: public
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"

