
version: 2

models:
  - name: patient_membership_client_B_common_format_dates
    description: |
      First point of ingestion of model that was imported to db by ingestion service.
      Normalized column fields to what we will work with going forward.
    columns:
      - name: member id
        description: Member id in format of ingested file
  # TO-DO: finish column documentation, not enough time in interview take home
  - name: patient_membership_client_B_latest_members_only
    description: |
      Reducing set of patients to only entries with latest end date for patient eligibility.

sources:
  - name: client_B_patient_source
    database: postgresdb
    schema: export
    tables:
      - name: patient_registration_clientB