version: 2

models:
  - name: membership_status
    description: |
      Gives status of members given their membership_end_date.
      Assumes first run is set at date of '2023-08-09'.
    columns:
      - name: status
        tests:
          - accepted_values:
              values: [ 'active', 'inactive' ]
    tests:
      - unique:
          column_name: member_id
      - data_type:
          table_name: membership_status
          column_name: membership_end_date
          desired: 'timestamp without time zone'
  - name: total_claim_payment_per_patient
    description: |
      Aggregated amount that each patient owes by the summation
      of their claims added up costs.
    tests:
      - unique:
          column_name: member_id
      - data_type:
          table_name: total_claim_payment_per_patient
          column_name: member_id
          desired: text
      - data_type:
          table_name: total_claim_payment_per_patient
          column_name: total_claims_payment
          desired: double precision
  - name: diagnosis_type
    description: |
      Given the primary diagnosis of a given claims, defines the
      diagnosis type of the specific diagnosis. Lists this out for each
      claim.
    columns:
      - name: diagnosis_type
        tests:
          - accepted_values:
              values: ['Behavioral disorder', 'Others', 'Chronic disease']
    tests:
      - data_type:
          table_name: diagnosis_type
          column_name: member_id
          desired: 'text'
      - data_type:
          table_name: diagnosis_type
          column_name: claim_number
          desired: 'text'
      - data_type:
          table_name: diagnosis_type
          column_name: primary_diagnosis
          desired: 'text'

